### ISSUE TITLE
cannot to reopen stdin: No such device or address

### ISSUE THREAD

**Issue by bjne** [okbob/pspg#35] opened 2017-11-19 19:51 UTC
When running psql with su:

``` bash
su postgres -c "psql test"

```
I get the following error:

``` sql
Line style is unicode.
Border style is 2.
Pager is used for long output.
Timing is on.
Null display is "¤".
psql (10.1)
Type "help" for help.

test=# select * from test;
cannot to reopen stdin: No such device or address
Time: 14.278 ms
test=#

```

**Comment by okbob** [comment] 2017-11-20 08:01
It is related to this code:
<pre>
    if (freopen("/dev/tty", "rw", stdin) == NULL)
    {
        fprintf(stderr, "cannot to reopen stdin: %s\n", strerror(errno));
        exit(1);
    }
</pre>
I am changing to switch from stdin (because it is used in pipe, and it is a change to interactive mode). It looks so command executed in this mode has not a access to tty. Now I have not idea, how it should be fixed.

**Comment by okbob** [comment] 2017-11-23 16:43
I am not sure if it is fixed correctly, but it looks like good workaround. Please, test it.

**Comment by bjne** [comment] 2017-11-25 12:41
Seems it is still a problem, this time with permission:

```
cannot to reopen stdin: Permission denied
```

**Comment by okbob** [comment] 2017-11-25 12:58
isn't is selinux issue? Now I cannot to reproduce it.

**Comment by bjne** [comment] 2017-11-25 13:19
No selinux

```
root@roadwarrior:~# echo 'testing 1-2-3'| su postgres -c "pspg"
cannot to reopen stdin: Permission denied
```

**Comment by okbob** [comment] 2017-11-25 13:50
I can reproduce it :-(

**Comment by okbob** [comment] 2017-11-25 14:59
I found a workaround, but probably not sure how much is secure or unsecure. You can run `tty` command instead `pspg` and you get number of `pts` device. Then you can allow rights:

    [pavel@nemesis pspg-master]$ chmod a+rw /dev/pts/3
    [pavel@nemesis pspg-master]$ su - postgres -c "PSQL_PAGER='/usr/local/bin/pspg -s 0' /usr/local/pgsql/bin/psql"

This is working

**Comment by bjne** [comment] 2017-11-25 15:43
wow-wow-wow, that is a horrible workaround. The problem is not that I am not able to make
use of pspg, but I think it should work the way I am executing it as well, I think you could accomplish
whatever you want with reopening terminal another way, that will also work with su user -c "pspg"

**Comment by okbob** [comment] 2017-11-25 15:47
yes, it is horrible workaround and doesn't work in fresh terminal. I have minimal knowledges about terminals, and I miss some about usage of ptsx

**Comment by okbob** [comment] 2017-11-25 16:22
su user -c "pspg" is not problem (not now, because the work with streams are ugly in pspg). In this case I have assigned terminal device in good mode. But when it is executed as nested command from psql, then I have not assigned stdin for interactive mode.

**Comment by okbob** [comment] 2017-11-26 07:21
@bjne - please, can you check cda02eae3b5685eeac182cb76851a18b0f57a22a ?

**Comment by bjne** [comment] 2017-11-26 09:01
This seems to work, great! Thanks for your attention to fixing!

**Comment by okbob** [comment] 2017-11-26 09:52
super

**Closed by okbob** 2017-11-26 09:52 UTC
Labels: bug
